### ISSUE TITLE
Add a discord icon to the README.md

### ISSUE THREAD

**Issue by sdake** [xertai/sdac#3]
Here is an example from a 🌶️  project made with ❤️ 

Committed in https://github.com/burn-rs/burn/commit/cadf494f1ee57bf2e4e826acc9f7eaeae9df72e9 by @nathanielsimard.

The readme renders nicely!

**Comment by lsdake** [comment]
Done!  Here's the pull request for it https://github.com/xertai/SDAC/pull/5

It doesn't fully work yet though because an admin needs to enable the widget setting on the discord server and I don't have admin privileges :) If you could do that it'd be very swag.  Once widgets are enabled it should just automatically start working!

https://shields.io/category/chat is the website used to make it; it has video instructions on how to enable widgets if needed lol

**Comment by sdake** [comment]
Thanks, @nathanielsimard. Community development is so excellent. Later today, I am going to give burn-rs a run. I was aware of shields.io, but @lsdake really dug in.

Nice job @lsdake !! This issue is part of PR: https://github.com/xertai/SDAC/pull/8.

After looking at your comment on this issue, it may make sense to go through the various shields available, identify the top six that fit well, and apply them. I created issue https://github.com/xertai/SDAC/issues/9.

**Comment by sdake** [comment]
Hi @lsdake, I just noticed you used your initials, @lsd...

**Comment by sdake** [comment]
@lsdake ,

this is the embed code
```
<iframe src="https://discord.com/widget?id=1018236355177881630&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>
```

It is now stored in SDAC's GitHub issues permanently.

**Comment by sdake** [comment]
@lsdake take a look: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by sdake** [comment]
I see you have the linking done in a different PR for the contribution guide. Good work!.

Closing this issue.
